#include<iostream>
using namespace std;
#include<string>

//常函数
class Person
{
public:
	//this指针的本质 是指针常量 指针的指向不可以修改
	//在成员函数后面加const,修饰的是this指，指针指向的值夜不可以修改
	void showPerson() const //const Person * const this
	{
		this->m_B = 100;
		//this->m_A = 100;//每个参数都带有this指针
		//this =NULL //this指针不可以修改指针的指向
	}

	int m_A;
	mutable  int m_B;//特殊变量，即使在常函数中，也可以修改这个值
};


void test01()
{
	Person p;
	p.showPerson();
}
//常对象
void test02()
{
	
  const	 Person p;//在对象前加const ,变成常对象
 // p.m_A = 100;
  p.m_B = 100;//是特殊值，在常对象下也可以修改
}

int main()
{




	system("pause");
	return 0;

}
